dataset:
  category: 'bird'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'train'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True
  num_pairs: 10000

  dir:
    texture: 'resources/color_maps/bird/map3.png'
    template: '/mnt/raid/csmteam/datasets/cachedir/cub/model/mean_bird_fixed.obj'
    data_dir: '/mnt/raid/csmteam/datasets/CUB_200_2011'
    cache_dir: '/mnt/raid/csmteam/datasets/cachedir/cub'

test:
  batch_size: 32
  epochs: 100
  shuffle: True
  workers: 4
  out_dir: '/mnt/raid/csmteam/out'
  use_gt_cam: True
  checkpoint: ''
  log:
    loss_step: 10
    image_summary_step: 30
    image_epoch: 1
