dataset:
  category: 'zebra'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'train'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True

  dir:
    texture: 'resources/color_maps/horse/map3.png'
    template: '/mnt/raid/csmteam/datasets/cachedir/models/zebra/zebra.obj'
    data_dir: '/mnt/raid/csmteam/datasets/ImageNet'
    cache_dir: '/mnt/raid/csmteam/datasets/cachedir'

train:
  batch_size: 2
  epochs: 200
  shuffle: True
  workers: 16
  checkpoint: ''
  out_dir: '/mnt/raid/csmteam/out/imnet'
  use_gt_cam: True
  use_sampled_cam: False
  use_arti: False
  num_in_chans: 3
  num_cam_poses: 8
  pose_warmup_step: 1000
  arti_epochs: 0
  log:
    image_summary_step: 10
    image_epoch: 1
  loss:
    geometric: 3.
    visibility: 4.
    mask: 2.
    diverse: 0.01
    quat: 0.1
  optim:
    lr: 0.0001
    beta1: 0.9
    type: 'adam'
