dataset:
  category: 'zebra'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'train'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True

  dir:
    texture: 'resources/color_maps/horse/map3.png'
    data_dir: '/mnt/raid/csmteam/datasets/ImageNet'
    cache_dir: '/mnt/raid/csmteam/datasets/cachedir'

train:
  batch_size: 16
  epochs: 250
  shuffle: True
  workers: 16
  checkpoint: ''
  out_dir: '/mnt/raid/csmteam/out'
  use_gt_cam: False
  use_sampled_cam: False
  num_cam_poses: 8
  pose_warmup_epochs: 10
  log:
    image_summary_step: 50
    image_epoch: 1
  loss:
    geometric: 1
    visibility: 10
    mask: 5
    diverse: 0.05
    quat: 0.1
  optim:
    lr: 0.0001
    beta1: 0.9
    type: 'adam'
