dataset:
  category: 'bird'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'train'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True

  dir:
    texture: 'resources/color_maps/bird/map3.png'
    template: 'datasets/cachedir/models/bird/bird.obj'
    data_dir: 'datasets/CUB_200_2011'
    cache_dir: 'datasets/cachedir'

train:
  batch_size: 5
  epochs: 100
  shuffle: True
  workers: 4
  checkpoint: ''
  out_dir: './out'
  use_gt_cam: True
  use_sampled_cam: False
  use_arti: False
  num_cam_poses: 8
  pose_warmup_step: 2000
  arti_epochs: 0
  log:
    image_summary_step: 30
    image_epoch: 1
  loss:
    geometric: 1
    visibility: 1
    mask: 1
    diverse: 0.05
    quat: 1
  optim:
    lr: 0.0001
    beta1: 0.9
    type: 'adam'
