dataset:
  category: 'car'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'train'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True

  dir:
    template: './datasets/cachedir/shapenet/car/marching_cubes_mean.obj'
    texture: 'resources/color_maps/car/map3.png'
    data_dir: './datasets/PASCAL3D+_release1.1'
    cache_dir: './datasets/cachedir/p3d'

train:
  batch_size: 5
  epochs: 100
  shuffle: True
  workers: 0
  checkpoint: ''
  out_dir: './out'
  use_gt_cam: True
  loss:
    geometric: 1
    visibility: 1
    mask: 2
  optim:
    lr: 0.00006
    beta1: 0.9
    type: 'adam'
