dataset:
  category: 'bird'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'test'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True
  num_pairs: 10000

  dir:
    texture: 'resources/color_maps/bird/map3.png'
    data_dir: '/mnt/raid/csmteam/datasets/CUB_200_2011'
    cache_dir: '/mnt/raid/csmteam/datasets/cachedir/cub'

test:
  batch_size: 1
  shuffle: True
  workers: 4
  out_dir: 'out/arti/test'
  use_gt_cam: True
  num_cam_poses: 8
  use_arti: False
   arti_epochs: 0
  num_in_chans_unet: 4
  num_in_chans: 3
  num_cam_poses: 8
  use_sampled_cam: True
  alpha: [0.05, 0.1, 0.2]
  checkpoint: ''
  add_summaries: True
  log:
    image_summary_step: 1
