dataset:
  category: 'bird'
  img_size: 256
  img_height: 320
  img_width: 512
  split: 'test'
  transform: 'flip'
  padding_frac: 0.05
  jitter_frac: 0.05
  flip: True
  tight_crop: False
  flip_train: True
  num_pairs: 10000

  dir:
    texture: 'resources/color_maps/bird/map3.png'
    data_dir: '/mnt/raid/csmteam/datasets/CUB_200_2011'
    cache_dir: '/mnt/raid/csmteam/datasets/cachedir/cub'

test:
  batch_size: 1
  shuffle: True
  workers: 8
  out_dir: '/mnt/raid/csmteam/out'
  use_gt_cam: True
  num_cam_poses: 8
  use_sampled_cam: True
  use_arti: True
  arti_epochs: 0
  alpha: [0.08, 0.1, 0.13]
  checkpoint: ''
  add_summaries: True
  log:
    image_summary_step: 1
